### PR TITLE
Nft lance UI 2

### PR DESCRIPTION
**Pull request by futuristfuturist**
This is 99% done, and I really want it merged. Otherwise I have to constantly rebase and resolve conflicts. I resolved all conflicts so it should merge easily. However, read this whole thing first. Some stuff needs to be added before the merge. 

**What does the code do:**
-It fixes the broken NFTLance process and UI:
    > The entire selling process is clear and works: a 1-2-3 stepper is added
    > The entire buying process is clear and works
    > Pick between 2 tokens how u want to be paid, no need to google for token address anymore
    > U can find your own NFTLance page with a button
    > U can find other people's NFTLance collections via their profile
    > It makes sure a buyer doesn't see buttons that only a seller should see on their own page
    > No more steps/pages that get stuck and have to be manually refreshed
    > No more pages that can only be accessed if u have the exact url
    > U can check for requests via a button and go back to your profile
    > URI field is removed (wasn't needed)
    > Bunch of other small things
-It adds a small alt text button/feature

IMPORTANT: **What needs to be added BEFORE or together with the merge:**
-This update nigeon made earlier:
 https://github.com/creaton-io/creaton/commit/89f37ae1b89fc6030e38dca02fa4faf126d889fd
 This update absolutely needs to be added before the merge, otherwise some stuff won't work. 
 update: done!
-connect the alt text again on graph, already have the instructions on how to do it.
-in this file https://github.com/creaton-io/creaton/commit/0f2567597fd57a3932bb91d168430fd2d1429161 commit,
there is an explanation on why "altText" has been removed from a line. It should be added there again, but only after the graph is connected, otherwise the landing becomes blank/empty. 

**What still needs to be done (and will be added shortly by me, AFTER the merge):**
-add/edit some copy/text at some pages/steps with more explanation with every step (got most the text already done, will add later, this will make everything even more clear for average users)
-tighten the design up a little bit more
-remove the added CSS from the main CSS file to a separate file or as JSX
-an extra field where people can fill in their own custom token address 
-other stuff later to be added (there is always more)

**What would also be nice to add, but is too much work for now:**
-make sellers add the meta data in Creaton itself on a form instead of on an external service (discussed with nigeon)

Even with these small things still to be done, the code should get merged. It's clear enough for now. When the explanation text is added its fully understandable. The details I will add later.

### CODE REVIEW

**Comment by nigeon** [comment]
removed node_modules, ran `npm i` and some errors:
`Error: Cannot find module 'mini-svg-data-uri'`

and:

`webpack 5.72.0 compiled with 2 errors and 303 warnings in 37945 ms
ERROR in src/App.test.tsx:8:23
TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.
     6 |   render(<App />);
     7 |   const linkElement = screen.getByText(/learn react/i);
  >  8 |   expect(linkElement).toBeInTheDocument();
       |                       ^^^^^^^^^^^^^^^^^
     9 | });
    10 |
`

please, always check npm dependencies are OK! Removing node_modules, and `npm i` is sadly something we must do  everytime when switching branches

**Comment by nigeon** [comment]
Just added the dependency on the npm and now it's fine. Will test the rest ;)

**Comment by nigeon** [comment]
I see now the texts are pending, but anyway: 

https://www.loom.com/share/28c22eec71c547ef90e5ac1468b396cf

**Comment by futuristfuturist** [comment]
> I see now the texts are pending, but anyway:
> 
> https://www.loom.com/share/28c22eec71c547ef90e5ac1468b396cf

Thanks for the feedback, I will try to fix what u just showed me.

Regarding texts / explanations in general, this is something that will be added. There are multiple places which
still need text / explanation, I'm gonna add them all at once.

**Comment by nigeon** [comment]
Pushed my pending changes ;)

**Pull request merged**
